//
//  CountryModel.swift
//  Maisarah
//
//  Created by Maulik Vora on 17/07/22.
//

import Foundation
//import ObjectMapper

class CountryData: Mappable {
    
    var name: String = ""
    var countryCode: String = ""
    var currency: String = ""
    
    init(countryCode: String? = nil, currency: String? = nil) {
        self.countryCode = countryCode ?? ""
        self.currency = currency ?? ""
    }

    required init?(map: Map) {
    }
    
    // Mappable
    func mapping(map: Map) {
        
    }
    
}

var countryListLocal:[CountryData] = [

    CountryData(countryCode:"ABW", currency: "AWG"),
    CountryData(countryCode:"AFG", currency: "AFN"),
    CountryData(countryCode:"AGO", currency: "AOA"),
    CountryData(countryCode:"AIA", currency: "XCD"),
    CountryData(countryCode:"ALA", currency: "N/A"),
    CountryData(countryCode:"ALB", currency: "ALL"),
    CountryData(countryCode:"AND", currency: "EUR"),
    CountryData(countryCode:"ARE", currency: "AED"),
    CountryData(countryCode:"ARG", currency: "ARS"),
    CountryData(countryCode:"ARM", currency: "AMD"),
    CountryData(countryCode:"ASM", currency: "USD"),
    CountryData(countryCode:"ATA", currency: "XCD"),
    CountryData(countryCode:"ATF", currency: "EUR"),
    CountryData(countryCode:"ATG", currency: "XCD"),
    CountryData(countryCode:"AUS", currency: "AUD"),
    CountryData(countryCode:"AUT", currency: "EUR"),
    CountryData(countryCode:"AZE", currency: "AZN"),

    CountryData(countryCode:"BDI",currency: "BIF"),
    CountryData(countryCode:"BEL",currency: "EUR"),
    CountryData(countryCode:"BEN",currency: "XOF"),
    CountryData(countryCode:"BFA",currency: "XOF"),
    CountryData(countryCode:"BGD",currency: "BDT"),
    CountryData(countryCode:"BGR",currency: "BGN"),
    CountryData(countryCode:"BHS",currency: "242"),
    CountryData(countryCode:"BIH",currency: "N/A"),
    CountryData(countryCode:"BLM",currency: "N/A"),
    CountryData(countryCode:"BLR",currency: "BYR"),
    CountryData(countryCode:"BLZ",currency: "BZD"),
    CountryData(countryCode:"BMU",currency: "441"),
    CountryData(countryCode:"BOL",currency: "BOB"),
    CountryData(countryCode:"BQ",currency: "N/A"),
    CountryData(countryCode:"BRA",currency: "BRL"),
    CountryData(countryCode:"BRB",currency: "246"),
    CountryData(countryCode:"BRN",currency: "BND"),
    CountryData(countryCode:"BTN",currency: "BTN"),
    CountryData(countryCode:"BVT",currency: "NOK"),
    CountryData(countryCode:"BWA",currency: "BWP"),

    CountryData(countryCode:"CAF",currency: "XAF"),
    CountryData(countryCode:"CAN",currency: "CAD"),
    CountryData(countryCode:"CCK",currency: "AUD"),
    CountryData(countryCode:"CHE",currency: "CHF"),
    CountryData(countryCode:"CHL",currency: "CLP"),
    CountryData(countryCode:"CHN",currency: "CNY"),
    CountryData(countryCode:"CIV",currency: "N/A"),
    CountryData(countryCode:"CMR",currency: "XAF"),
    CountryData(countryCode:"COD",currency: "XAF"),
    CountryData(countryCode:"COG",currency: "CDF"),
    CountryData(countryCode:"COK",currency: "NZD"),
    CountryData(countryCode:"COL",currency: "COP"),
    CountryData(countryCode:"COM",currency: "KMF"),
    CountryData(countryCode:"CPV",currency: "CVE"),
    CountryData(countryCode:"CRI",currency: "CRC"),
    CountryData(countryCode:"CUB",currency: "CUP"),
    CountryData(countryCode:"CW",currency: "N/A"),
    CountryData(countryCode:"CXR",currency: "AUD"),
    CountryData(countryCode:"CYM",currency: "KYD"),
    CountryData(countryCode:"CYP",currency: "EUR"),
    CountryData(countryCode:"CZE",currency: "CZK"),

    CountryData(countryCode:"DEU",currency: "EUR"),
    CountryData(countryCode:"DJI",currency: "DJF"),
    CountryData(countryCode:"DMA",currency: "DOP"),
    CountryData(countryCode:"DNK",currency: "DKK"),
    CountryData(countryCode:"DOM",currency: "DOP"),
    CountryData(countryCode:"DZA",currency: "DZD"),

    CountryData(countryCode:"ECU",currency: "ECS"),
    CountryData(countryCode:"EGY",currency: "EGP"),
    CountryData(countryCode:"ERI",currency: "ERN"),
    CountryData(countryCode:"ESH",currency: "MAD"),
    CountryData(countryCode:"ESP",currency: "EUR"),
    CountryData(countryCode:"EST",currency: "EUR"),
    CountryData(countryCode:"ETH",currency: "ETB"),

    CountryData(countryCode:"FIN",currency: "EUR"),
    CountryData(countryCode:"FJI",currency: "FJD"),
    CountryData(countryCode:"FLK",currency: "FKP"),
    CountryData(countryCode:"FRA",currency: "EUR"),
    CountryData(countryCode:"FRO",currency: "DKK"),
    CountryData(countryCode:"FSM",currency: "USD"),

    CountryData(countryCode:"GAB",currency: "XAF"),
    CountryData(countryCode:"GB_ENG",currency: "GBP"),
    CountryData(countryCode:"GB_NIR",currency: "GBP"),
    CountryData(countryCode:"GB_SCT",currency: "GBP"),
    CountryData(countryCode:"GB_WLS",currency: "GBP"),
    CountryData(countryCode:"GBR",currency: "GBP"),
    CountryData(countryCode:"GEO",currency: "GEL"),
    CountryData(countryCode:"GGY",currency: "GGP"),
    CountryData(countryCode:"GHA",currency: "GHS"),
    CountryData(countryCode:"GIB",currency: "GIP"),
    CountryData(countryCode:"GIN",currency: "GNF"),
    CountryData(countryCode:"GLP",currency: "EUR"),
    CountryData(countryCode:"GMB",currency: "GMD"),
    CountryData(countryCode:"GNB",currency: "GWP"),
    CountryData(countryCode:"GNQ",currency: "XAF"),
    CountryData(countryCode:"GRC",currency: "EUR"),
    CountryData(countryCode:"GRD",currency: "XCD"),
    CountryData(countryCode:"GRL",currency: "DKK"),
    CountryData(countryCode:"GTM",currency: "QTQ"),
    CountryData(countryCode:"GUF",currency: "EUR"),
    CountryData(countryCode:"GUM",currency: "USD"),
    CountryData(countryCode:"GUY",currency: "GYD"),

    CountryData(countryCode:"HKG",currency: "HKD"),
    CountryData(countryCode:"HMD",currency: "AUD"),
    CountryData(countryCode:"HND",currency: "HNL"),
    CountryData(countryCode:"HRV",currency: "HRK"),
    CountryData(countryCode:"HTI",currency: "HTG"),
    CountryData(countryCode:"HUN",currency: "HUF"),

    CountryData(countryCode:"IDN",currency: "IDR"),
    CountryData(countryCode:"IMN",currency: "GBP"),
    CountryData(countryCode:"IND",currency: "INR"),
    CountryData(countryCode:"IOT",currency: "USD"),
    CountryData(countryCode:"IRL",currency: "EUR"),
    CountryData(countryCode:"IRN",currency: "IRR"),
    CountryData(countryCode:"IRQ",currency: "IQD"),
    CountryData(countryCode:"ISL",currency: "ISK"),
    CountryData(countryCode:"ISR",currency: "ILS"),
    CountryData(countryCode:"ITA",currency: "EUR"),

    CountryData(countryCode:"JAM",currency: "JMD"),
    CountryData(countryCode:"JET",currency: "N/A"),
    CountryData(countryCode:"JOR",currency: "JOD"),
    CountryData(countryCode:"JPN",currency: "JPY"),

    CountryData(countryCode:"KAZ",currency: "KZT"),
    CountryData(countryCode:"KEN",currency: "KES"),
    CountryData(countryCode:"KGZ",currency: "KGS"),
    CountryData(countryCode:"KHM",currency: "KHR"),
    CountryData(countryCode:"KIR",currency: "AUD"),
    CountryData(countryCode:"KNA",currency: "XCD"),
    CountryData(countryCode:"KOR",currency: "KRW"),
    CountryData(countryCode:"KWT",currency: "KWD"),

    CountryData(countryCode:"LAO",currency: "LAK"),
    CountryData(countryCode:"LBN",currency: "LBP"),
    CountryData(countryCode:"LBR",currency: "LRD"),
    CountryData(countryCode:"LBY",currency: "LYD"),
    CountryData(countryCode:"LCA",currency: "XCD"),
    CountryData(countryCode:"LIE",currency: "CHF"),
    CountryData(countryCode:"LKA",currency: "LKR"),
    CountryData(countryCode:"LSO",currency: "LSL"),
    CountryData(countryCode:"LTU",currency: "LTL"),
    CountryData(countryCode:"LUX",currency: "EUR"),
    CountryData(countryCode:"LVA",currency: "LVL"),

    CountryData(countryCode:"MAC",currency: "N/A"),
    CountryData(countryCode:"MAF",currency: "Euro"),
    CountryData(countryCode:"MAR",currency: "MAD"),
    CountryData(countryCode:"MCO",currency: "EUR"),
    CountryData(countryCode:"MDA",currency: "MDL"),
    CountryData(countryCode:"MDG",currency: "MGF"),
    CountryData(countryCode:"MDV",currency: "MVR"),
    CountryData(countryCode:"MEX",currency: "MXN"),
    CountryData(countryCode:"MHL",currency: "USD"),
    CountryData(countryCode:"MKD",currency: "MKD"),
    CountryData(countryCode:"MLI",currency: "XOF"),
    CountryData(countryCode:"MLT",currency: "EUR"),
    CountryData(countryCode:"MMR",currency: "MMK"),
    CountryData(countryCode:"MNE",currency: "EUR"),
    CountryData(countryCode:"MNG",currency: "MNT"),
    CountryData(countryCode:"MNP",currency: "USD"),
    CountryData(countryCode:"MOZ",currency: "MZN"),
    CountryData(countryCode:"MRT",currency: "MRO"),
    CountryData(countryCode:"MSR",currency: "XCD"),
    CountryData(countryCode:"MTQ",currency: "EUR"),
    CountryData(countryCode:"MUS",currency: "MUR"),
    CountryData(countryCode:"MWI",currency: "MWK"),
    CountryData(countryCode:"MYS",currency: "MYR"),
    CountryData(countryCode:"MYT",currency: "EUR"),

    CountryData(countryCode:"NAM",currency: "NAD"),
    CountryData(countryCode:"NCL",currency: "XPF"),
    CountryData(countryCode:"NER",currency: "XOF"),
    CountryData(countryCode:"NFK",currency: "AUD"),
    CountryData(countryCode:"NGA",currency: "NGN"),
    CountryData(countryCode:"NIC",currency: "NIO"),
    CountryData(countryCode:"NIU",currency: "NZD"),
    CountryData(countryCode:"NLD",currency: "EUR"),
    CountryData(countryCode:"NOR",currency: "NOK"),
    CountryData(countryCode:"NPL",currency: "NPR"),
    CountryData(countryCode:"NRU",currency: "AUD"),
    CountryData(countryCode:"NZL",currency: "NZD"),
    CountryData(countryCode:"OMN",currency: "OMR"),
    CountryData(countryCode:"PAK",currency: "PKR"),
    CountryData(countryCode:"PAN",currency: "PAB"),
    CountryData(countryCode:"PCN",currency: "NZD"),
    CountryData(countryCode:"PER",currency: "PEN"),
    CountryData(countryCode:"PHL",currency: "PHP"),
    CountryData(countryCode:"PLW",currency: "USD"),
    CountryData(countryCode:"PNG",currency: "PGK"),
    CountryData(countryCode:"POL",currency: "PLN"),
    CountryData(countryCode:"PRI",currency: "USD"),
    CountryData(countryCode:"PRK",currency: "KPW"),
    CountryData(countryCode:"PRT",currency: "EUR"),
    CountryData(countryCode:"PRY",currency: "PYG"),
    CountryData(countryCode:"PSE",currency: "N/A"),
    CountryData(countryCode:"PYF",currency: "EUR"),

    CountryData(countryCode:"QAT",currency: "QAR"),

    CountryData(countryCode:"REU",currency: "EUR"),
    CountryData(countryCode:"ROU",currency: "RON"),
    CountryData(countryCode:"RUS",currency: "RUB"),
    CountryData(countryCode:"RWA",currency: "RWF"),

    CountryData(countryCode:"SAU",currency: "SAR"),
    CountryData(countryCode:"SDN",currency: "SDG"),
    CountryData(countryCode:"SEN",currency: "XOF"),
    CountryData(countryCode:"SGP",currency: "SGD"),
    CountryData(countryCode:"SGS",currency: "GBP"),
    CountryData(countryCode:"SHN",currency: "SHP"),
    CountryData(countryCode:"SJM",currency: "NOK"),
    CountryData(countryCode:"SLB",currency: "SBD"),
    CountryData(countryCode:"SLE",currency: "SLL"),
    CountryData(countryCode:"SLV",currency: "SVC"),
    CountryData(countryCode:"SMR",currency: "EUR"),
    CountryData(countryCode:"SOM",currency: "SOS"),
    CountryData(countryCode:"SPM",currency: "EUR"),
    CountryData(countryCode:"SRB",currency: "RSD"),
    CountryData(countryCode:"SSD",currency: "SSP"),
    CountryData(countryCode:"STP",currency: "STD"),
    CountryData(countryCode:"SUR",currency: "SRD"),
    CountryData(countryCode:"SVK",currency: "EUR"),
    CountryData(countryCode:"SVN",currency: "EUR"),
    CountryData(countryCode:"SWE",currency: "SEK"),
    CountryData(countryCode:"SWZ",currency: "SZL"),
    CountryData(countryCode:"SX",currency: "N/A"),
    CountryData(countryCode:"SYC",currency: "SCR"),
    CountryData(countryCode:"SYR",currency: "SYP"),

    CountryData(countryCode:"TCA",currency: "USD"),
    CountryData(countryCode:"TCD",currency: "XAF"),
    CountryData(countryCode:"TGO",currency: "XOF"),
    CountryData(countryCode:"THA",currency: "THB"),
    CountryData(countryCode:"TJK",currency: "TJS"),
    CountryData(countryCode:"TKL",currency: "NZD"),
    CountryData(countryCode:"TKM",currency: "TMT"),
    CountryData(countryCode:"TLS",currency: "N/A"),
    CountryData(countryCode:"TON",currency: "TOP"),
    CountryData(countryCode:"TTO",currency: "TTD"),
    CountryData(countryCode:"TUN",currency: "TND"),
    CountryData(countryCode:"TUR",currency: "TRY"),
    CountryData(countryCode:"TUV",currency: "AUD"),
    CountryData(countryCode:"TWN",currency: "TWD"),

    CountryData(countryCode:"TZA",currency: "TZS"),

    CountryData(countryCode:"UGA",currency: "UGX"),
    CountryData(countryCode:"UKR",currency: "UAH"),
    CountryData(countryCode:"UMI",currency: "UMI"),
    CountryData(countryCode:"URY",currency: "UYU"),
    CountryData(countryCode:"USA",currency: "USD"),
    CountryData(countryCode:"UZB",currency: "UZS"),

    CountryData(countryCode:"VAT",currency: "EUR"),
    CountryData(countryCode:"VCT",currency: "XCD"),
    CountryData(countryCode:"VEN",currency: "EUR"),
    CountryData(countryCode:"VGB",currency: "USD"),
    CountryData(countryCode:"VIR",currency: "USD"),
    CountryData(countryCode:"VNM",currency: "VND"),
    CountryData(countryCode:"VUT",currency: "VUV"),
    CountryData(countryCode:"WLF",currency: "XPF"),
    CountryData(countryCode:"WSM",currency: "WST"),

    CountryData(countryCode:"XK",currency: "N/A"),

    CountryData(countryCode:"YEM",currency: "YER"),

    CountryData(countryCode:"ZAF",currency: "ZAR"),
    CountryData(countryCode:"ZMB",currency: "ZMW"),
    CountryData(countryCode:"ZWE",currency: "ZWD")
    
   ]
